# Generated by Django 5.2.5 on 2025-09-05 05:35

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestedDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                ("original_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(blank=True, default="", max_length=100)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("num_chunks", models.IntegerField(default=0)),
                ("status", models.CharField(default="processed", max_length=30)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
